### ISSUE TITLE
[feat] support `--secrets` argument when creating functions/connectors

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsarctl#1096]
in `pulsar-admin functions/sinks/sources create` command, there's an argument for passing secret ref:

```
    --secrets
      The map of secretName to an object that encapsulates how the secret is
      fetched by the underlying secrets provider #Java, Python
```

We need this arguments in pulsarctl to allow user safely access secrets

**Comment by shibd** [comment]
Done by #1125
