### ISSUE TITLE
[feat] support `--available-sinks` --available-sources` argument when listing built-in connectors

### ISSUE THREAD

**Issue by Huanli-Meng** [streamnative/pulsarctl#1098]
`pulsar-admin` has a command `pulsar-admin sinks available-sinks`  or `pulsar-admin sources available-sources` to list all available built-in sink or source connectors on SN Cloud hosted cluster. 

We need this arguments in pulsarctl to allow users list all available built-in sink or source connectors on SN Cloud hosted cluster.

**Comment by Huanli-Meng** [comment]
@momo-jun this has an impact on our docs. Could you please help look into it when you update connector docs?

**Comment by momo-jun** [comment]
> @momo-jun this has an impact on our docs. Could you please help look into it when you update connector docs?

Thanks, Huanli. Yes, we've included the commands in the docs.
