### ISSUE TITLE
Add `context` resource to pulsarctl

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsarctl#119]
*Problem*

Currently users have to specify the cluster url when running commands. It will be great if pulsarctl provides a `context` resource, so pulsarctl can switch the `default` clusters between contexts.

**Comment by EronWright** [comment]
One idea to consider for the future is to provide a go package that numerous CLIs could use to parse the context configuration.   In other words, `pulsarctl` is likely not the only tool that will make use of the configuration file.  Similarly, `kubectl` delegates to the [cli-runtime](https://github.com/kubernetes/cli-runtime) library.

**Comment by EronWright** [comment]
Some ideas that occurred to me while trying this new feature:
1. Add a `standalone` context by default.
2. Automatically `use` a context when it is added.
3. Eliminate the default service url of `http://localhost:8080`, i.e. always assume a context.
4. Provide an `add` in addition to `set`.
5. Should `broker list <cluster-name>` be updated to use context in some way?
6. Set a default tenant and/or namespace into the context (for convenience in working with topics, functions, sources, sinks etc).   i.e. eliminate the defaults depicted below:
```
    pulsarctl source list
      --tenant public
      --namespace default
```

**Comment by sijie** [comment]
@EronWright Nice suggestions! 

@wolfstudy can you create issues for these improvements? So we can plan these improvements for subsequent releases.

**Comment by wolfstudy** [comment]
> Provide an add in addition to set.

Currently, the context `set` command has both `add` and `set` functions. 

Thanks @EronWright 



> @wolfstudy can you create issues for these improvements? So we can plan these improvements for subsequent releases.

Of course, will create these tasks to track them.

**Comment by EronWright** [comment]
@wolfstudy To clarify (6), I'd like to be able to set a tenant and/or namespace which would be used by default in various commands.  For example:
```
$ pulsarctl context set --current --tenant foo --namespace bar
(context updated)

$ pulsarctl topic list
+--------------------------------------------------+---------------+
|                    TOPIC NAME                    | PARTITIONED ? |
+--------------------------------------------------+---------------+
| persistent://foo/bar/topic-27                    | Y             |
| persistent://foo/bar/topic-28                    | Y             |
...
```

Note that `kubectl` has this same functionality for working with namespace.  From the [cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/):
```
# permanently save the namespace for all subsequent kubectl commands in that context.
$ kubectl config set-context --current --namespace=ggckad-s2
```

**Comment by wolfstudy** [comment]
> @wolfstudy To clarify (6), I'd like to be able to set a tenant and/or namespace which would be used by default in various commands. For example:
> 
> ```
> $ pulsarctl context set --current --tenant foo --namespace bar
> (context updated)
> 
> $ pulsarctl topic list
> +--------------------------------------------------+---------------+
> |                    TOPIC NAME                    | PARTITIONED ? |
> +--------------------------------------------------+---------------+
> | persistent://foo/bar/topic-27                    | Y             |
> | persistent://foo/bar/topic-28                    | Y             |
> ...
> ```
> 
> Note that `kubectl` has this same functionality for working with namespaces. From the [cheatsheet](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-context-and-configuration):
> 
> ```
> # permanently save the namespace for all subsequent kubectl commands in that context.
> $ kubectl config set-context --current --namespace=ggckad-s2
> ```

@EronWright Nice suggestions! 

But at present, I didn't think of a simple way to implement this function, this feature is too invasive to the original code

**Comment by wolfstudy** [comment]
@EronWright i will close the issue, we can discuss the issue at https://github.com/streamnative/pulsarctl/issues/173
