### ISSUE TITLE
Support different ways to dump the result

### ISSUE THREAD

**Issue by zymap** [streamnative/pulsarctl#126]
improve the CLI by adding an option `-o` or `--output` to dump the results, either PLAIN, TABLE, or JSON.

**Comment by EronWright** [comment]
Progress:

- [ ] Add top-level `-o` flag (with `TABLE` as default)
- [ ] Implement a general framework for output formatting
- [ ] Implement `TABLE` format
- [ ] Implement `PLAIN` format
- [ ] Implement `JSON` format
- [ ] Write integration test(s)
