### ISSUE TITLE
functions querystate generates invalid API request when `--key` not provided

### ISSUE THREAD

**Issue by candlerb** [streamnative/pulsarctl#131]
If you run the `pulsarctl functions querystate` command without the `--key` option, you get:

```
$ ./pulsarctl functions querystate --name womble
error: Unknown pulsar error
```

Digging with tcpdump on port 3080, the HTTP exchange can be seen as:

```
GET /admin/v3/functions/public/default/womble/state HTTP/1.1
Host: localhost:8080
User-Agent: Pulsarctl-Go-v0.1.0
Accept: application/json
Content-Type: application/json
Accept-Encoding: gzip

HTTP/1.1 404 Not Found
Date: Sat, 02 Nov 2019 08:27:18 GMT
Cache-Control: must-revalidate,no-cache,no-store
Content-Length: 0
Server: Jetty(9.4.12.v20180830)
```

That is: pulsarctl is making a HTTP request to a URL which is not defined as part of the REST API.

ISTM that the `--key` argument should be made mandatory.

To be fair: the `--key` argument is optional in pulsar-admin too; but in that case pulsar-admin [crashes](https://github.com/apache/pulsar/issues/5533) with a null pointer exception before it sends any request to the REST API.

**Comment by wolfstudy** [comment]
Thanks @candlerb work for this, the issue has been fixed in [pr:130](https://github.com/streamnative/pulsarctl/pull/130/files#diff-51787263b7fa144cfb6b487d3132b59bR152)

```
$ ./pulsarctl functions querystate --name word_count_1

Error: required flag(s) "key" not set
Usage: pulsarctl functions querystate [flags]
```
