### ISSUE TITLE
Topics operates should redirect to the owner broker

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/pulsarctl#148]
The following operations should redirect to the owner broker, otherwise the `pulsarctl` will block and can't return any information.

1. compact-status
2. internal-info
3. internal-stats
4. last-message-id
5. offload
6. offload-status
7. stats
8. unload

**Comment by sijie** [comment]
@wolfstudy @zymap don't we configure the http client to follow redirections?

**Comment by wolfstudy** [comment]
> @wolfstudy @zymap don't we configure the http client to follow redirections?

The `net/http` Client will automatically handle redirects by default. The reasons for this issue are as follows:
- Cookies lost on redirect
- Does not comply with Go's default redirection rules
- ...

**Comment by sijie** [comment]
@wolfstudy can you improve the integration tests to cover the redirect case to see if you can run the above commands with redirections? If `pulsarctl` doesn't handle redirect correctly, we need to fix it.

**Comment by codelipenghui** [comment]
@sijie It's my mistaken

**Comment by sijie** [comment]
@codelipenghui sure.

@wolfstudy but I think we should add tests to cover redirection cases.
