### ISSUE TITLE
investigate how pulsarctl can integrate with gcloud

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsarctl#161]
*Motivation*

investigate how pulsarctl can integrate with different cloud providers and come up with a design.

**Comment by EronWright** [comment]
I observe that some go-based CLIs support a plugin model via sub-processes.  For example, `pulsarctl gcloud foo` would search the `PATH` for an executable called `pulsarctl-gcloud`.

`kubectl` uses this approach, see: [Extend kubectl with plugins](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) and [the list of known plugins](https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md).

**Comment by sijie** [comment]
@EronWright good point. I think we can consider adding the plugin framework to pulsarctl so that we can build the plugin ecosystem for pulsarctl. This can be a good item for pulsarctl 0.4.0.

**Comment by sijie** [comment]
Created an issue for tracking adding a plugin/extension framework to pulsarctl. #179
