### ISSUE TITLE
Provide GPG signature and SHA3-512 hashsum for binaries

### ISSUE THREAD

**Issue by lanwen** [streamnative/pulsarctl#222]
Thank you for the project!

Since pulsar is a mission critical software for us, it would be nice to add some security for the installation process from the binaries. It would be great to have a way of validating the correct hashsum and signature of the binary.

**Comment by sijie** [comment]
@wolfstudy @zymap can any of you take a look at this and improve our release process to include hashsum and signature of the binary like what we did for pulsar binary distribution?

**Comment by jiazhai** [comment]
Add key for all component in SN platform releases

**Comment by sijie** [comment]
@jiazhai I don't think we should close this issue. The issue should be left open. @zymap just changed a different way to release these assets.

**Comment by sijie** [comment]
@zymap: please update README file to include the asc signature files.

**Comment by zymap** [comment]
Because we have multiple platform executable files and we already link to the release page, it's might we don't need to provide asc and sha512 link in the README.md.
