### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by lanwen** [streamnative/pulsarctl#223]
Maybe I missing something, but is that possible to omit table view and get values directly?
Like instead of 
```
+------------------------------+
|        SUBSCRIPTIONS         |
+------------------------------+
| signup                       |
```

just output directly:

```
signup
```
?

As for now its hard to create any chain of calls or use the output in scripts

**Comment by sijie** [comment]
@lanwen `pulsarctl` supports specifying output format using `-o` or `--output`. Currently it supports `json`, `yaml` and `text`. You can use json as the output and chain the commands using jq.

```bash
$ pulsarctl tenants list -o yaml
- public
- pulsar
- streamnative
```

```bash
$ pulsarctl tenants list -o json
[
  "public",
  "pulsar",
  "streamnative"
]
```

```bash
$ pulsarctl tenants list -o text
+--------------+
| TENANT NAME  |
+--------------+
| public       |
| pulsar       |
| streamnative |
+--------------+
```

**Comment by lanwen** [comment]
Okay, now found it here
https://github.com/streamnative/pulsarctl/blob/master/docs/en/developer-guide.md#output-configuration

Thank you!
