### ISSUE TITLE
[Question]Use the env for token

### ISSUE THREAD

**Issue by liangyuanpeng** [streamnative/pulsarctl#227]
I have to add the --token paramter when i use pulsarctl in the auth request, Can i use the env for token?

Please remind me if I missed something! 

Thank!

**Comment by sijie** [comment]
@zymap @wolfstudy can any of you help answer this requestion?

**Comment by wolfstudy** [comment]
> I have to add the --token paramter when i use pulsarctl in the auth request, Can i use the env for token?

Thanks @liangyuanpeng feedback, this is a good idea, maybe we can support the feature.

Currently, we do not yet support this option as env, or you can use `pulsarctl context` set this.
