### ISSUE TITLE
Outdated docs for namespaces set-retention command

### ISSUE THREAD

**Issue by pylebecq** [streamnative/pulsarctl#238]
Hello. 👋 

I'm currently trying to use pulsarctl (0.4.1) to do some operations on a Pulsar 2.6.0 cluster.

The documentation for the namespaces set-retention command seems wrong or at least is missing some details.

The two examples on the [documentation](https://streamnative.io/docs/pulsarctl/v0.4.1/#-em-set-retention-em-) are the following:

```sh
pulsarctl namespaces set-retention tenant/namespace --time 100m

pulsarctl namespaces set-retention tenant/namespace --size 1G
```

They are wrong because both `--time` and `--size` options are required. So you get the following result in both cases:

```
Error: required flag(s) "time" not set
Usage: pulsarctl namespaces set-retention [flags]

Examples:
    #Set the retention policy for a namespace
    pulsarctl namespaces set-retention tenant/namespace --time 100m

    #Set the retention policy for a namespace
    pulsarctl namespaces set-retention tenant/namespace --size 1G

[...]
```

Also, it says to use `-1` to infinite time or size retention.

However, when using `-1` for the `--time` it fails with the following error:

```
$ pulsarctl --admin-service-url=http://localhost:8080 namespaces set-retention public/default --size 1G --time -1                                          
[✖]  invalid time '-'
```

Same result when adding quotes to `"-1"`.

What's the proper way to specify infinite time retention?

**Comment by zymap** [comment]
@pylebecq  
For specified a negative number, you need to add `--`  before the negative number. You can try:
```
pulsarctl --admin-service-url=http://localhost:8080 namespaces set-retention public/default --size 1G --time -- -1         
```

**Comment by sijie** [comment]
@zymap Can you add this to the help message?

**Comment by zymap** [comment]
sure

**Comment by pylebecq** [comment]
@zymap Thank you for your reply. However, this also does not work:

```
$ pulsarctl --admin-service-url=http://localhost:8080 namespaces set-retention public/default --size 1G --time -- -1
Error: unknown shorthand flag: '1' in -1
```

**Comment by zymap** [comment]
@pylebecq Sorry for my late response. It seems something wrong in the code. https://github.com/streamnative/pulsarctl/blob/master/pkg/ctl/namespace/set_retention.go#L118
I will fix it as soon as possible.

**Comment by pylebecq** [comment]
@zymap Thank you for fixing it!
