### ISSUE TITLE
Cannot Create Topics Programmatically

### ISSUE THREAD

**Issue by JamWils** [streamnative/pulsarctl#247]
There seems to be some inconsistencies when using pulsarctl directly from a Go application.  For example, when I go to create a new topic using admin.Topics().Create(utils.TopicName, int) it calls for utils.TopicName, but all of the fields on that struct are private so you cannot in fact create a topic.  This is from v0.5.0

```
type TopicName struct {
	domain         TopicDomain
	tenant         string
	namespace      string
	topic          string
	partitionIndex int

	namespaceName *NameSpaceName
}
```

This doesn't seems intentional, I just wasn't sure how much pulsarctl is meant to be used on the command-line versus being a wrapper around the Admin SDK that we can leverage in code.

Actually, looking at the rest of the interface, all of the functions seem to have this issue.  My guess is that this isn't intended to be used outside of the command-line tool itself.  Topics is an exposed interface though.

**Comment by codelipenghui** [comment]
@zymap @wolfstudy Could you please help take a look at this issue? @JamWils I think the right way is to use `admin.Topics().Create()`

**Comment by JamWils** [comment]
My bad, I updated the example above, it is `admin.Topics().Create`, using `admin.Tenants().Create` was a typo on my part.

**Comment by wolfstudy** [comment]
Yes, Maybe we need to expose the fields in TopicName.

**Comment by smazurov** [comment]
@JamWils why not do this:

```golang
_ = admin.Topics().Create(utils.GetTopicName("persistent://default/public/my-awesome-topic"), 4)
```

I don't know intentions of the original authors of `pulsarctl`, but it can certainly be used outside of CLI. Check out `terraform-pulsar-provider` for other examples.

**Comment by JamWils** [comment]
Yeah, you're right.  Having it in a complete separate package like that seems a little wonky which is how I missed it, but that function does a really good good at parsing the string and populating the topic name.  I'm going to close this issue.  I really don't think it's worth making those fields public if this exists.
