### ISSUE TITLE
Default admin api version is v1 instead of v2

### ISSUE THREAD

**Issue by milos-matijasevic** [streamnative/pulsarctl#248]
As here states [example.go](https://github.com/streamnative/pulsarctl/blob/master/examples.go#L42) default `APIVersion` should be `v2`, but when i run this example i got `v1` as default `APIVersion` (also with `v1` version admin api doesn't work for me)

![image](https://user-images.githubusercontent.com/38222386/97305705-c620de00-185d-11eb-80ea-749b56c07dcf.png)

**Comment by zymap** [comment]
Sorry for the delay. @milos-matijasevic 
That seems there has a bug. Would you like to fix it?
Or you can use another API that can specify the API version.

**Comment by milos-matijasevic** [comment]
sure, I will make a pr
