### ISSUE TITLE
Cannot install by brew

### ISSUE THREAD

**Issue by bry00** [streamnative/pulsarctl#261]
An attempt to install the `pulsarctl` module using brew fails with the message: `Error: An exception occurred within a child process: Errno::EISDIR: Is a directory - read`.

My environment:
- macOS Big Sur:, version: 11.0.1
- go version go1.15.6 darwin/amd64

Here is a full installation log:
```console
#  brew install pulsarctl
Updating Homebrew...
==> Installing pulsarctl from streamnative/streamnative
==> Cloning https://github.com/streamnative/pulsarctl.git
Updating /Users/xyz/Library/Caches/Homebrew/pulsarctl--git
==> Checking out tag v0.5.0
HEAD is now at 615bbc7 Release version 0.5.0
HEAD is now at 615bbc7 Release version 0.5.0
==> go build
Error: An exception occurred within a child process:
  Errno::EISDIR: Is a directory - read
```

**Comment by sijie** [comment]
Thank you for reporting the issue! We just noticed the error and we will fix it soon.

**Comment by zymap** [comment]
This issue already addressed by this https://github.com/streamnative/homebrew-streamnative/pull/16. I will close this issue and feel free to reopen it if has any question.

**Comment by bry00** [comment]
Super, thx.
