### ISSUE TITLE
Update copyright for pulsarctl

### ISSUE THREAD

**Issue by tuteng** [streamnative/pulsarctl#373]
![image](https://user-images.githubusercontent.com/1907867/122136550-4d66a480-ce75-11eb-934b-2779a0551a16.png)

**Comment by zymap** [comment]
Does this need to change to 2021? @tuteng

**Comment by tuteng** [comment]
Yes, we can consider using the following function to implement it if possible:
```
Copyright © ${new Date().getFullYear()} StreamNative, Inc.
```
@zymap
