### ISSUE TITLE
`--tls-enable-hostname-verification` is not available in context

### ISSUE THREAD

**Issue by sijie** [streamnative/pulsarctl#433]
It seems that there is no way to configure `--tls-enable-hostname-verification` in context.

**Comment by nodece** [comment]
Hi @sijie, I check out this codebase and apache/pulsar codebase, I found the `--tls-enable-hostname-verification` and `--tls-allow-insecure` are the same. If there are the same, we should keep one. 

If I miss anything, please let me know.
