### ISSUE TITLE
Version command is fail

### ISSUE THREAD

**Issue by zymap** [streamnative/pulsarctl#441]
**Motivation**

When releasing the pulsarctl, the scripts don't add the version flags so we can not know the pulsarctl version. We should add the flags in the build scripts.

**Comment by ericsyh** [comment]
Does this issue mean that pulsarctl binary released from github workflow do not support version flags?

**Comment by zymap** [comment]
@ericsyh No. Sorry for the wrong description. That's caused by the flag is not set when building the pulsarctl.
