### ISSUE TITLE
TopicAutoCreationConfig has Allow bool to false by default and not null

### ISSUE THREAD

**Issue by KannarFr** [streamnative/pulsarctl#703]
I recently had this https://github.com/apache/pulsar/issues/15452 issue. I just dived into it and it seems to be related to the pulsarctl implementation which has a `TopicAutoCreationConfig` type with `Allow` as boolean and I think the false value is sent as `policies.autoTopicCreationOverride` during namespace creation.

This issue prevent auto topic creation without any configuration by default.

**Comment by nodece** [comment]
Could you provide the pulsarctl version?

**Comment by nodece** [comment]
This issue has been fixed by https://github.com/streamnative/pulsarctl/pull/556.

**Comment by nodece** [comment]
You need to upgrade to v2.10.x, which includes this fix.
