### ISSUE TITLE
An update to a sink shouldn't have a default value in AutoAck or Retain Ordering

### ISSUE THREAD

**Issue by AlvaroStream** [streamnative/pulsarctl#751]
When we try to update a sink, we receive an error like this ones:
- AutoAck cannot be altered
- Retain Ordering cannot be altered

The default value updating the sink is trying to be imposed on the sink returning the error.

Maybe --auto-ack shouldn't be allowed to be updated on the sink and [set always to null](https://github.com/apache/pulsar/blob/50d1c05c88020f178f813035a6287c01feba53b8/pulsar-functions/utils/src/main/java/org/apache/pulsar/functions/utils/SinkConfigUtils.java#L592-L594). As other values like Retain Ordering or RetainKeyOrdering.

**Comment by nodece** [comment]
@AlvaroStream Thanks for your report! Please keep the same value when updating to avoid this issue. Because of to limit by the cli, we cannot provide a null value.

**Comment by nodece** [comment]
@AlvaroStream I submitted https://github.com/streamnative/pulsarctl/pull/873 to fix this.
