### ISSUE TITLE
Cannot create topic names with colons in them. 

### ISSUE THREAD

**Issue by david-streamlio** [streamnative/pulsarctl#827]
When trying to create a topic with a colon in the name, it appears that the topic name gets URL encoded, trying to create a topic named persistent://jbgs/default/cv:test:vechicle_detected results in a topic named "persistent://jbgs/default/cv%3test%3vechicle_detected" being created

Can you fix this behavior to prevent the URL encoding of special characters?

**Comment by nodece** [comment]
Good idea, we shouldn't encode the topic name, I'll create a PR to fix this today.
