### ISSUE TITLE
Proposal: pulsarctl configure from declarative YAML manifest

### ISSUE THREAD

**Issue by tsturzl** [streamnative/pulsarctl#844]
So I've been working on a private project that is currently using pulsarctl's internals to allow me to specify a configuration for several namespaces and topics using YAML and subsequently create those topics and namespaces with the given configuration, or if they already exists to update them  with the given configuration. This basically gives you the ability to manage the configuration of namespaces and topics through a declarative YAML manifest. I'm wondering if this is something that might be a useful feature to add to pulsarctl, maybe with an `apply` sub command which points at a YAML file and configures the pulsar client and reusing much of the existing CLI to configure the pulsar admin client.

The benefit here is that you don't have to create long ugly boot strap scripts to setup Pulsar initially, and then subsequently to update it. Instead you have a single configuration that you easily apply regardless of whether it's creating the resources or updating them, you're just bringing it up to a known and defined configuration as defined by the manifest.

I wonder if there is interest in including this in the pulsarctl project, or perhaps this strays too far from the intent of this project. I would be more than happy to make major contributions to this feature.

**Comment by nodece** [comment]
Looks like: https://github.com/streamnative/terraform-provider-pulsar?

**Comment by EronWright** [comment]
Another option: https://github.com/streamnative/pulsar-resources-operator

**Comment by tsturzl** [comment]
There are great recommendations. I hadn't heard of either of these, and they seem to be difficult to find unless you know specifically what you're looking for. In this case I don't currently use terraform for any projects, so I'd never thought to look for it. I hadn't seen the operator either, we currently use the helm charts for deployment.

**Comment by addisonj** [comment]
Thanks for the feedback @tsturzl 

One of the things we have been working on is getting the terraform provider up on the terraform registry so that should help with visibility there.

For the pulsar resource operator, that is open source, but something we have been working closely with a few customers on developing, but if you have interest in using it, we would love feedback :) 

Just so you know, the pulsar-resources-operator builds upon this library :)

**Comment by tsturzl** [comment]
@addisonj Awesome! I appreciate it. I think we'll try out the k8s operator as we currently aren't using terraform for anything. The admin API client in is well designed and fairly easy to use. I was trying to write my own based on the API docs, and provided swagger but subtle differences between pulsar versions made it more of a headache that I was hoping for. I look forward to trying out the operator.
