### ISSUE TITLE
ambiguous import

### ISSUE THREAD

**Issue by z774379121** [streamnative/pulsarctl#866]
`   github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 tested by
        github.com/apache/pulsar-client-go/oauth2.test imports
        github.com/apache/pulsar-client-go/oauth2/clock/testing loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/clock/testing in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2\clock\testing)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b\clock\testing)
`

[https://github.com/apache/pulsar-client-go/pull/802](https://github.com/apache/pulsar-client-go/pull/802)
pulsar-client-go removed the  sub-module of oauth2, but github.com/apache/pulsar-client-go/oauth2 still in go.mod under pulsarctl.

**Comment by nodece** [comment]
Could you share your command?

**Comment by z774379121** [comment]
> Could you share your command?

module temples

go 1.18

require (
	github.com/apache/pulsar-client-go v0.9.0
	github.com/spf13/viper v1.9.0
	github.com/streamnative/pulsarctl v2.10.1.3
)

`go mod tidy
go: downloading github.com/streamnative/pulsarctl v0.4.3-0.20221028055535-7ca24d1acd24
wplive/cmd/avprocess/oss imports
        github.com/aliyun/aliyun-oss-go-sdk/oss imports
        golang.org/x/time/rate loaded from golang.org/x/time@v0.0.0-20191024005414-555d28b269f0,
        but go 1.16 would select v0.0.0-20201208040808-7e3f01d25324
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2 in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b)
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/cache loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/cache in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2\cache)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b\cache)
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/clock loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/clock in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2\clock)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b\clock)
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2/store loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/store in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2\store)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b\store)
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/linkedin/goavro/v2 imports
        github.com/golang/snappy loaded from github.com/golang/snappy@v0.0.1,
        but go 1.16 would select v0.0.3
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 imports
        github.com/golang-jwt/jwt loaded from github.com/golang-jwt/jwt@v3.2.1+incompatible,
        but go 1.16 would select v3.2.2+incompatible
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 tested by
        github.com/apache/pulsar-client-go/oauth2.test imports
        github.com/apache/pulsar-client-go/oauth2/clock/testing loaded from github.com/apache/pulsar-client-go@v0.9.0,
        but go 1.16 would fail to locate it:
        ambiguous import: found package github.com/apache/pulsar-client-go/oauth2/clock/testing in multiple modules:
        github.com/apache/pulsar-client-go v0.9.0 (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go@v0.9.0\oauth2\clock\testing)
        github.com/apache/pulsar-client-go/oauth2 v0.0.0-20211108044248-fe3b7c4e445b (C:\Users\user\go\pkg\mod\github.com\apache\pulsar-client-go\oauth2@v0.0.0-20211108044248-fe3b7c4e445b\clock\testing)
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 imports
        github.com/golang-jwt/jwt tested by
        github.com/golang-jwt/jwt.test imports
        github.com/golang-jwt/jwt/request loaded from github.com/golang-jwt/jwt@v3.2.1+incompatible,
        but go 1.16 would select v3.2.2+incompatible
wplive/pkg/messagebus/pulsar imports
        github.com/apache/pulsar-client-go/pulsar imports
        github.com/apache/pulsar-client-go/pulsar/internal/auth imports
        github.com/apache/pulsar-client-go/oauth2 imports
        github.com/golang-jwt/jwt tested by
        github.com/golang-jwt/jwt.test imports
        github.com/golang-jwt/jwt/test loaded from github.com/golang-jwt/jwt@v3.2.1+incompatible,
        but go 1.16 would select v3.2.2+incompatible

To upgrade to the versions selected by go 1.16, leaving some packages unresolved:
        go mod tidy -e -go=1.16 && go mod tidy -e -go=1.17
If reproducibility with go 1.16 is not needed:
        go mod tidy -compat=1.17
For other options, see:
        https://golang.org/doc/modules/pruning`

**Comment by z774379121** [comment]
> Could you share your command?

Fixed after clean go mod cache.
